version: "3.4"
services:
  favicon-manager:
    image: homer-favicon-manager
    build:
      context: .
    environment:
      VERIFY_SSL: 0
    volumes:
      - ./vol:/data
  homer:
    image: b4bz/homer:v23.02.2
    volumes:
      - ./vol:/www/assets
    ports:
      - 8080:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=0
